version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: syllabus-tracker-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: syllabus_tracker
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - syllabus-tracker-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: syllabus-tracker-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/syllabus_tracker?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
    ports:
      - "5001:5000"
    depends_on:
      - mongodb
    networks:
      - syllabus-tracker-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: syllabus-tracker-frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:5000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - syllabus-tracker-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongodb_data:

networks:
  syllabus-tracker-network:
    driver: bridge
